# Generated by Django 4.1.13 on 2026-04-01 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('is_master', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantKeycloakConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('server_url', models.URLField(help_text='Base Keycloak URL e.g. https://keycloak.example.com')),
                ('realm', models.CharField(help_text='Keycloak realm name — must match tenant slug', max_length=128)),
                ('client_id', models.CharField(max_length=256)),
                ('client_secret', models.CharField(blank=True, help_text='Leave blank for public clients (PKCE-only)', max_length=512)),
                ('discovery_url', models.URLField(blank=True, help_text='Auto-filled: {server_url}/realms/{realm}/.well-known/openid-configuration')),
                ('authorization_endpoint', models.URLField(blank=True)),
                ('token_endpoint', models.URLField(blank=True)),
                ('userinfo_endpoint', models.URLField(blank=True)),
                ('jwks_uri', models.URLField(blank=True)),
                ('end_session_endpoint', models.URLField(blank=True)),
                ('scopes', models.CharField(default='openid email profile', help_text='Space-separated OIDC scopes', max_length=256)),
                ('claim_username', models.CharField(default='preferred_username', max_length=64)),
                ('claim_email', models.CharField(default='email', max_length=64)),
                ('claim_name', models.CharField(default='name', max_length=64)),
                ('claim_groups', models.CharField(default='groups', help_text='Keycloak claim that contains group memberships', max_length=64)),
                ('pkce_enabled', models.BooleanField(default=True)),
                ('pkce_method', models.CharField(choices=[('S256', 'SHA-256'), ('plain', 'Plain')], default='S256', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keycloak_config', to='tenant_platform.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantAdminBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_platform_admin', models.BooleanField(default=False, help_text='True only for master tenant admins who can manage all tenants')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_bindings', to='tenant_platform.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_admin_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
