# Generated by Django 4.1.13 on 2026-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantkeycloakconfig',
            name='default_role',
            field=models.CharField(default='User', help_text='Default JumpServer role for users with no matching Keycloak group', max_length=64),
        ),
        migrations.AddField(
            model_name='tenantkeycloakconfig',
            name='role_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Map Keycloak groups to JumpServer roles. Format: {"keycloak-group": "JumpServerRole"} Valid roles: SystemAdmin, OrgAdmin, OrgAuditor, User'),
        ),
    ]
